Add queue/requeue commands for lear
Signed-off-by: Ian Costanzo <ian@anon-solutions.ca>

diff --git a/openshift/manage b/openshift/manage
--- a/openshift/manage
+++ b/openshift/manage
@@ -75,6 +75,20 @@ usage () {
         Example:
           $0 -e dev queueOrganization 54321
 
+    requeueOrganizationLear <corp_num>
+      - Use with caution.  Requeue a specific company that may have already been processed.
+        Where:
+          - <corp_num>, is the corp_num from corp_history_log for the organization to requeue/reprocess.
+        Example:
+          $0 -e dev requeueOrganizationLear 54321
+
+    queueOrganizationLear <corp_num>
+      - Use with caution.  Queue a specific company that has *not* already been processed.
+        Where:
+          - <corp_num>, is the corp_num from BC Registries for the organization to queue/process.
+        Example:
+          $0 -e dev queueOrganizationLear 54321
+
     getPipelineStatus
       - Get the pipeline status for the given environment.
         Runs the './run-step.sh bcreg/display_pipeline_status.py' pipeline script
@@ -578,7 +592,45 @@ queueOrganization() {
   # Queue affected event_by_corp_filing records
   runInContainer -v \
     ${_podName}${resourceSuffix} \
-    "psql -d "'${POSTGRESQL_DATABASE}'" -ac \"insert into event_by_corp_filing (system_type_cd, corp_num, prev_event_id, prev_event_date, last_event_id, last_event_date, entry_date) select system_type_cd, '${_corpNum}', 0, '0001-01-01', last_event_id, last_event_date, now() from event_by_corp_filing where record_id = (select max(record_id) from event_by_corp_filing);\""
+    "psql -d "'${POSTGRESQL_DATABASE}'" -ac \"insert into event_by_corp_filing (system_type_cd, corp_num, prev_event_id, prev_event_date, last_event_id, last_event_date, entry_date) select 'BC_REG', '${_corpNum}', 0, '0001-01-01', last_event_id, last_event_date, now() from event_by_corp_filing where record_id = (select max(record_id) from event_by_corp_filing);\""
+}
+
+requeueOrganizationLear() {
+  _corpNum=${1}
+  _podName=${2}
+  if [ -z "${_corpNum}" ] || [ -z "${_podName}" ]; then
+    echo -e \\n"requeueOrganizationLear; Missing parameter!"\\n
+    exit 1
+  fi
+
+  # Remove affected credential_log records
+  runInContainer -v \
+    ${_podName}${resourceSuffix} \
+    "psql -d "'${POSTGRESQL_DATABASE}'" -ac \"delete from credential_log where corp_num in ('${_corpNum}');\""
+
+  # Remove affected corp_history_log records
+  runInContainer -v \
+    ${_podName}${resourceSuffix} \
+    "psql -d "'${POSTGRESQL_DATABASE}'" -ac \"delete from corp_history_log where corp_num in ('${_corpNum}');\""
+
+  # Requeue affected event_by_corp_filing records
+  runInContainer -v \
+    ${_podName}${resourceSuffix} \
+    "psql -d "'${POSTGRESQL_DATABASE}'" -ac \"update event_by_corp_filing set process_success = null, process_date = null, process_msg = null where corp_num in ('${_corpNum}');\""
+}
+
+queueOrganizationLear() {
+  _corpNum=${1}
+  _podName=${2}
+  if [ -z "${_corpNum}" ] || [ -z "${_podName}" ]; then
+    echo -e \\n"queueOrganizationLear; Missing parameter!"\\n
+    exit 1
+  fi
+
+  # Queue affected event_by_corp_filing records
+  runInContainer -v \
+    ${_podName}${resourceSuffix} \
+    "psql -d "'${POSTGRESQL_DATABASE}'" -ac \"insert into event_by_corp_filing (system_type_cd, corp_num, prev_event_id, prev_event_date, last_event_id, last_event_date, entry_date) select 'BCREG_LEAR', '${_corpNum}', 0, '0001-01-01', last_event_id, last_event_date, now() from event_by_corp_filing where record_id = (select max(record_id) from event_by_corp_filing);\""
 }
 
 function getPipelineStatus() {
